### ISSUE TITLE
create re-boot board for paris and push latest fixes

### ISSUE THREAD

**Issue by lucarioams** [windingtree/stays-eth-paris#1]
- [x] create re-boot project board [x] - DONE - see https://github.com/orgs/windingtree/projects/24/views/1
- [ ] update code base with latest code from Barca repo

**Comment by lucarioams** [comment]
cool yeah also when creating a new issue you can create it on the two boards at the same time, if it is relevant to both.

**Comment by valera-rozuvan** [comment]
Code up to date.
