### ISSUE TITLE
Landing page is not user friendly 

### ISSUE THREAD

**Issue by vsomsen** [windingtree/stays-eth-paris#14]
### Operating System

macOS (amd)

### What browsers are you seeing the problem on?

Chrome

### Describe the bug

Suggested fix: shorten it to "EthCC" instead of "Ethereum Community Conference 5" and fix the position. 

<img width="1429" alt="Screenshot 2022-06-22 at 10 55 15" src="https://user-images.githubusercontent.com/104916620/175001525-f2339135-8321-4acb-8e13-75960843fbc6.png">

**Comment by lucarioams** [comment]
The issue is the positioning of the picture on the background that has Paris written on it, I actually told Max and the designers that the reason I changed the pic for Barcelona was because of that...

**Comment by lucarioams** [comment]
should we put another solarpunk image?
