### ISSUE TITLE
Hard code Hoy Paris and alter Hyatt 

### ISSUE THREAD

**Issue by vsomsen** [windingtree/stays-eth-paris#16]
### Describe the bug

Not really a bug...

See updated availabilities in the picture attached. 

No min. stays.

<img width="493" alt="Screenshot 2022-06-22 at 12 54 35" src="https://user-images.githubusercontent.com/104916620/175023014-bddeae63-e85b-4fff-8b81-29d9f0a5cf36.png">

**Comment by lucarioams** [comment]
@vsomsen you can select the different form, as feature request or just make a blank issue if it is not a bug.
